---
title: "DataFest"
toc: true
---

## Brief description

Over the weekend of April 4-6, you will work with a completely new-to-you dataset to answer some research question(s) of interest! More details on the [Middlebury DataFest website](https://midd-datafest-2025.github.io/home.html)!

In small groups, you will work to answer the research question(s) of interest using methods we've thus far learned in the class.

Because of the extra time-commitment of DataFest, the problem set associated with Week 7 will be light/combined into a problem set with Week 8!

## Key dates

| Deliverable | What/where | Date |
|------------------------|------------------------|------------------------|
| Group formation | Email Prof. Tang (one per group) | Thursday 3/27 at 11:59pm |
| Register for DataFest | [DataFest website](https://midd-datafest-2025.github.io/home.html), "Register" tab (each person must do so) | Monday 3/31 in class |
| DataFest opening ceremony | Q-Center (MBH 202) | Friday 4/4 at 6:00pm |
| Work on DataFest project | Q-Center (MBH 202) | Anytime from opening ceremony-Sunday 4/6 11:00am |
| Submit deliverable | Rendered `.qmd` report submitted to Canvas | Sunday 4/6 11:00am |
| Project presentations (either rendered report or brief slides) | Q-Center (MBH 202) | Sunday 4/6 11:00am-1:00pm (depending on time slot) |

## Requirements

### Group creation

You will work in groups of 2-3 people.

By the due date listed in the table above, you should either:

1.  form a group of three on your own and then e-mail Prof. Tang your decision, cc-ing everyone in the group
2.  form a group of two and then e-mail Prof. Tang your decision, cc-ing the other person in the group.
    -   Your group of two may be randomly paired with another person
3.  e-mail Prof. Tang if you don't have a preference and/or want to meet new people and would like to be randomly placed in a group

**While not binding, you should view the people you work with on DataFest as people who you might like to work on the final project with.**

Once all groups have been formed, Prof. Tang will confirm them and we will register for DataFest as a class on Monday 3/31.

### DataFest participation

-   You must attend the DataFest opening ceremony on Friday 4/4 at 6:00pm in the Q-Center. At the ceremony you will learn about the data and the research questions

-   **In addition to the opening ceremony, it is my expectation that your group works for at least 3 hours on the project over the course of the weekend.**

    -   Your whole group need not work together at the same time, but I highly encourage it all the same!

    -   Your are certainly welcome to work more than 3 hours!

-   There will be plenty of mentors on-site to help you will bugs. Prof. Tang will specifically be there at times TBD.

-   You will be asked to sign-up to present your finalized product to a panel of judges on Sunday 4/6 somewhere between 11am-1pm. Your entire group should attend the presentations (more details below).

### Report

You will be asked to create and submit a well-written report (in the form a rendered `.qmd`) that answers some or all of the research question(s) using a mix of both:

1.  Compelling visualizations and summary tables, and

2.  Simulation-based techniques (one of which must be in the form of a hypothesis test)

Your report should include:

1.  A brief introduction
2.  For each research question of interest:
    i.  Details of cleaning/wrangling of the data you performed to answer the question
    ii. A description of the methods you used to answer the question
    iii. The actual result+interpretation in context (e.g. a visualization, confidence interval, conduct hypothesis test)
3.  A brief conclusion about what you might do differently or things that were particularly challenging

### Presentation

Each group will givne an oral presentation of their project to a panel of judges. Prizes will be awarded in several categories. For your presentation, you should either accompany your presentation with:

-   A brief set of slides (preferred), or

-   Your rendered report

## Grading

TBD
