---
title: "Schedule"
page-layout: full
format: 
  html:
    css: styles.css
---

Jump to:

-   [Week 1](#week1)
-   [Week 2](#week2)

+--------------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Week         | Date     | In-class material                                                                                                                                                                         | Coding practice                                                                                                                                       | Assignments                                                                                                                        |
+:============:+==========+===========================================================================================================================================================================================+=======================================================================================================================================================+====================================================================================================================================+
| ::: {#week1} | M 2/10   | -   Topic: [Welcome!](slides/slides-00-welcome.qmd)                                                                                                                                       |                                                                                                                                                       | -   Submit [Problem Set 0](homework/hw0.qmd) **before 2/12** class                                                                 |
| **1**        |          |     -   Directions for printing at bottom                                                                                                                                                 |                                                                                                                                                       | -   Try to install R and RStudio **before Thursday's 2/13 class** using [these instructions](slides/installation_instructions.qmd) |
| :::          |          |                                                                                                                                                                                           |                                                                                                                                                       |                                                                                                                                    |
+--------------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
|              | W 2/12   | -   Topic: [Study design](slides/slides-01-study-design.qmd) (pdf [here](slides/pdf/slides-01.pdf))                                                                                       |                                                                                                                                                       | -   Install R and RStudio **before Thursday class** using [these instructions](slides/installation_instructions.qmd)               |
|              |          |     -   [Practice problems](practice_probs/practice-01-study-design.qmd)                                                                                                                  |                                                                                                                                                       | -   Wednesday problems on [Problem Set 1](homework/hw1.pdf)                                                                        |
+--------------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
|              | R 2/13   | -   Topic: [Programming toolkit](slides/slides-02-toolkit.qmd) (no need to print slides!)                                                                                                 | -   Intro to R and Quarto Markdown                                                                                                                    | -   Thursday problems on [Problem Set 1](homework/hw1.pdf)                                                                         |
|              |          |     -   [RStudio help sheet](slides/02-rstudio_help_sheet.qmd)                                                                                                                            |                                                                                                                                                       |                                                                                                                                    |
|              |          | -   `R` and `.qmd` [basics](live_code/intro_R.qmd)                                                                                                                                        |     {{< downloadthis coding_practice/coding-practice-02-intro-r.qmd dname="coding-practice-intro-R" label="Coding practice" id=mtcars-btn >}}         |                                                                                                                                    |
|              |          |     -   Download the following .qmd template and drag to your new STAT 201 folder: {{< downloadthis live_code/template_intro_R.qmd dname="intro_R" label="qmd template" id=mtcars-btn >}} |                                                                                                                                                       |                                                                                                                                    |
+--------------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| ::: {#week2} | M 2/17   | -   Topic: [Numerical data](slides/slides-03-numerical-pt1.qmd) (pdf [here](slides/pdf/slides-03.pdf))                                                                                    |                                                                                                                                                       | -   Monday problems on [Problem Set 2](homework/hw2.pdf)                                                                           |
| **2**        |          |                                                                                                                                                                                           |                                                                                                                                                       |                                                                                                                                    |
| :::          |          |                                                                                                                                                                                           |                                                                                                                                                       |                                                                                                                                    |
+--------------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
|              | W 2/19   | -   Topic: [Numerical data (part 2)](slides/slides-04-numerical-pt2.qmd) (pdf [here](slides/pdf/slides-04.pdf))                                                                           | -   Numerical data                                                                                                                                    | -   Wednesday problems on [Problem Set 2](homework/hw2.pdf)                                                                        |
|              |          |                                                                                                                                                                                           |                                                                                                                                                       |                                                                                                                                    |
|              |          |                                                                                                                                                                                           |     {{< downloadthis coding_practice/coding-practice-04-numerical-pt2.qmd dname="coding-practice-numerical" label="Coding practice" id=mtcars-btn >}} |                                                                                                                                    |
+--------------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
|              | R 2/20   | -   Topic: [Visualizations with ggplot](slides/slides-05-numerical-data-viz.qmd) (pdf [here](slides/pdf/slides-05.pdf))                                                                   | -   Introduction to ggplot                                                                                                                            | -   Thursday problems on [Problem Set 2](homework/hw2.pdf) (i.e. the following coding exercises)                                   |
|              |          |     -   Live code template                                                                                                                                                                |                                                                                                                                                       |                                                                                                                                    |
|              |          |                                                                                                                                                                                           |     {{< downloadthis coding_practice/coding-practice-05-ggplot.qmd dname="coding-practice-ggplot" label="Coding practice" id=mtcars-btn >}}           |     {{< downloadthis homework/hw2_r.qmd dname="hw2_r" label="hw2_r" id=mtcars-btn >}}                                              |
|              |          |         {{< downloadthis live_code/live_code_notes.qmd dname="live_code_notes" label=".qmd" id=mtcars-btn >}}                                                                             |                                                                                                                                                       |                                                                                                                                    |
+--------------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[10,10,40,40\]"}

To print PDF of the slides with multiple slides on a page:

1.  Download the PDF and open the document
2.  Print the document
    i.  In the Print options, go to *Layout* then choose your preferred number of *Pages per Sheet*
    ii. Hit *Print*
